# Generated by Django 4.2 on 2024-02-28 06:53

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(max_length=150)),
                ('State', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=30)),
                ('serorprod', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('imgurl', models.CharField(default='', max_length=1000)),
                ('feature_vector', pgvector.django.VectorField(dimensions=1536)),
            ],
        ),
    ]
