# Generated by Django 4.2 on 2024-04-18 08:42

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_experiences_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledgeext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('chunk', models.CharField(max_length=1000)),
                ('feature_vector', pgvector.django.VectorField(dimensions=1536)),
            ],
        ),
    ]
